[package]
name = "canvord-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
web-sys = { version = "0.3.77", features = ["Storage"] }
sycamore = { version = "0.9.1", features = ["serde"] }
serde = { version = "1.0.2", features = ["derive"] }
serde_json = "1.0.2"
sycamore-router = "0.9.1"