[package]
name = "canvord-service"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
entity = { path = "../entity" }

[dependencies.sea-orm]
version = "1.1.12"
features = [
    "debug-print",
    "runtime-tokio-rustls",
    "sqlx-mysql"
]