name: canvord

services:
  canvord-sqldata:
    image: "mysql:8.0"
    environment:
      - MYSQL_ROOT_PASSWORD=114514
      - MYSQL_DATABASE=canvord
    volumes:
      - canvord-sqldata:/var/lib/mysql
    networks:
      - canvord-network
    ports:
      - "33306:3306"


networks:
  canvord-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/24


volumes:
  canvord-sqldata:
    external: false