name: canvord

services:
  canvord-sqldata:
    image: "mysql:8.0"
    environment:
      - MYSQL_ROOT_PASSWORD=Pass@word
    volumes:
      - canvord-sqldata:/var/lib/mysql
    networks:
      - canvord-network
    ports:
      - "35206:3306"

  canvord-textitemapi:
    image: canvord-textitemapi
    build:
      context: .
      dockerfile: src/contrib/text_item_api/Dockerfile
    networks:
      - canvord-network
    ports:
      - "35210:8080"
      - "50001"

  canvord-textitemapi-dapr:
    image: "daprio/daprd:latest"
    network_mode: "service:canvord-textitemapi"
    depends_on:
      - canvord-textitemapi
    command: [ "./daprd",
               "-app-id", "canvord-textitemapi",
               "-app-port", "8080",
               "-components-path", "/components",
               "-config", "/configuration/canvord-configuration.yaml" ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    restart: always

networks:
  canvord-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/24
  
volumes:
  canvord-sqldata:
    external: false
  canvord-rabbitmq-data:
    external: false
  canvord-rabbitmq-log:
    external: false