//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "text_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub item_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_type = "Binary(16)")]
    pub user_identity_uuid: Uuid, //Vec<u8>,
    pub is_deleted: bool, // i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
