[package]
name = "services"
version = "0.1.0"
edition = "2021"

[dependencies]
entity = { path = "../entity" }
async-trait = "0.1.88"

[dependencies.sea-orm]
version = "1.1.11"
features = [
    "debug-print",
    "runtime-tokio-rustls",
    "sqlx-mysql"
]