[package]
name = "canvord_backend"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
canvord-api = { path = "api" }

[workspace]
members = [".", "api", "dto", "service", "entity", "migration", "service", "command", "handler", "middleware"]
